const bpMonthInput=document.querySelector('#bp-month');
const bpStatus=document.querySelector('#bp-status');
const bpTable=document.querySelector('#bp-table');
const bpHistory=document.querySelector('#bp-history');
const bpMonthLabel=month=>new Intl.DateTimeFormat('pt-BR',{month:'short',year:'2-digit',timeZone:'UTC'}).format(new Date(`${month}-01T00:00:00Z`));
const bpNumber=value=>value===null?'—':new Intl.NumberFormat('pt-BR',{maximumFractionDigits:0}).format(value);
const bpMoney=value=>value===null?'—':new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:2}).format(value);
const bpPercent=value=>value===null?'—':`${(value*100).toLocaleString('pt-BR',{maximumFractionDigits:2})}%`;
const bpPp=value=>value===null?'—':`${value>=0?'+':''}${(value*100).toLocaleString('pt-BR',{maximumFractionDigits:2})} p.p.`;
const bpGap=(value,type)=>value===null?'—':type==='rate'?bpPp(value):type==='money'?`${value>=0?'+':''}${bpMoney(value)}`:`${value>=0?'+':''}${bpNumber(value)}`;
function bpDefinition(month){const plan=window.BUSINESS_PLAN.months[month];const received=key=>DashboardData.valueFor(dataset,month,key);const appointments=received('appointments'),meetings=received('connections'),sales=received('sales'),revenue=received('revenue');return [
  {key:'calls',label:'Ligações',type:'count',plan:plan?.calls??null,actual:null,reason:'Discador não conectado'},
  {key:'schedulingRate',label:'Tx Ag.',type:'rate',plan:plan?.schedulingRate??null,actual:null,reason:'Discador não conectado'},
  {key:'appointments',label:'Agendamentos',type:'count',plan:plan?.appointments??null,actual:appointments},
  {key:'connectionRate',label:'Tx Conexões',type:'rate',plan:plan?.connectionRate??null,actual:appointments===null||appointments===0||meetings===null?null:meetings/appointments},
  {key:'meetings',label:'Reuniões',type:'count',plan:plan?.meetings??null,actual:meetings},
  {key:'conversionRate',label:'Tx Conversão',type:'rate',plan:plan?.conversionRate??null,actual:meetings===null||meetings===0||sales===null?null:sales/meetings},
  {key:'sales',label:'Vendas',type:'count',plan:plan?.sales??null,actual:sales},
  {key:'revenue',label:'Receita',type:'money',plan:plan?.revenue??null,actual:revenue},
  {key:'ticket',label:'TM',type:'money',plan:plan?.ticket??null,actual:DashboardData.valueFor(dataset,month,'ticket')}
];}
function bpFormat(value,type){return type==='rate'?bpPercent(value):type==='money'?bpMoney(value):bpNumber(value);}
function bpDiagnosis(row,planned){if(row.reason)return row.reason;if(row.plan===null)return 'Meta não cadastrada';if(row.actual===null)return 'Realizado indisponível';const gap=row.actual-planned;if(row.type==='rate'){const pp=gap*100;if(Math.abs(pp)<=2)return 'Taxa próxima da meta';return pp<0?`${Math.abs(pp).toLocaleString('pt-BR',{maximumFractionDigits:1})} p.p. abaixo da meta`:`${pp.toLocaleString('pt-BR',{maximumFractionDigits:1})} p.p. acima da meta`;}
 if(planned===0)return 'Sem meta comparável';const completion=row.actual/planned;if(completion>=.95)return `${(completion*100).toLocaleString('pt-BR',{maximumFractionDigits:0})}% do planejado até hoje`;if(completion>=.75)return `Ritmo abaixo: ${(completion*100).toLocaleString('pt-BR',{maximumFractionDigits:0})}% do planejado até hoje`;if(completion>=.5)return `Ritmo insuficiente: ${(completion*100).toLocaleString('pt-BR',{maximumFractionDigits:0})}% do planejado até hoje`;return `Distante do plano: ${(completion*100).toLocaleString('pt-BR',{maximumFractionDigits:0})}% do planejado até hoje`;}
function bpRender(){const month=bpMonthInput.value;if(!month)return;const targetDate=month===dataset.asOfDate.slice(0,7)?dataset.asOfDate:`${month}-${String(new Date(Date.UTC(+month.slice(0,4),+month.slice(5,7),0)).getUTCDate()).padStart(2,'0')}`;const elapsed=DashboardData.businessDayOrdinal(targetDate,dataset);const total=DashboardData.businessDaysInMonth(month,dataset);const ratio=Math.min(1,elapsed/total);const rows=bpDefinition(month).map(row=>({...row,planned:row.type==='rate'?row.plan:row.plan===null?null:row.plan*ratio}));
 bpStatus.textContent=`Planejamento até o ${elapsed}º dia útil de ${total} (${new Intl.DateTimeFormat('pt-BR',{timeZone:'UTC'}).format(new Date(`${targetDate}T00:00:00Z`))}). Fins de semana e feriados nacionais não entram no cálculo.`;
 bpTable.innerHTML=`<div class="table-scroll"><table><caption>Meta do mês versus ritmo até o mesmo dia útil. “—” indica dado ainda indisponível.</caption><thead><tr><th>Indicador</th><th>Plano mês</th><th>Planejado até hoje</th><th>Realizado</th><th>Gap</th><th>Diagnóstico</th></tr></thead><tbody>${rows.map(row=>{const gap=row.actual===null||row.planned===null?null:row.actual-row.planned;return `<tr><th scope="row">${escapeHTML(row.label)}</th><td>${bpFormat(row.plan,row.type)}</td><td>${bpFormat(row.planned,row.type)}</td><td>${bpFormat(row.actual,row.type)}</td><td class="${gap===null?'':gap<0?'gap-negative':'gap-positive'}">${bpGap(gap,row.type)}</td><td class="diagnosis">${escapeHTML(bpDiagnosis(row,row.planned))}</td></tr>`;}).join('')}</tbody></table></div>`;
 const first=(dataset.range?.start||month).slice(0,7),months=[];for(let cursor=first;cursor<=month;){months.push(cursor);const [year,m]=cursor.split('-').map(Number);cursor=`${m===12?year+1:year}-${String(m===12?1:m+1).padStart(2,'0')}`;}
 const historicalRows=bpDefinition(month).map(current=>({label:current.label,key:current.key,type:current.type}));
 bpHistory.innerHTML=`<div class="table-scroll"><table><caption>Em cada célula: BP / realizado. As metas só aparecem nos meses cadastrados.</caption><thead><tr><th>Indicador</th>${months.map(m=>`<th>${escapeHTML(bpMonthLabel(m))}</th>`).join('')}</tr></thead><tbody>${historicalRows.map(indicator=>`<tr><th scope="row">${escapeHTML(indicator.label)}</th>${months.map(m=>{const r=bpDefinition(m).find(item=>item.key===indicator.key),target=window.BUSINESS_PLAN.months[m]?.[indicator.key]??null;return `<td><span class="bp-cell-plan">${target===null?'Meta —':`BP ${bpFormat(target,indicator.type)}`}</span><span class="bp-cell-actual">Real. ${bpFormat(r?.actual??null,indicator.type)}</span></td>`;}).join('')}</tr>`).join('')}</tbody></table></div>`;}
bpMonthInput.value=dataset.asOfDate?.slice(0,7)||currentMonth;bpMonthInput.min=dataset.range?.start||bpMonthInput.value;bpMonthInput.max=dataset.range?.end||bpMonthInput.value;bpMonthInput.addEventListener('change',bpRender);bpRender();
